bookinfoRatings:
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
ratings:
  ports:
  - name: http
    port: 9080
    targetPort: 0
  type: ClusterIP
ratingsV1:
  ratings:
    image:
      repository: docker.io/istio/examples-bookinfo-ratings-v1
      tag: 1.18.0
    imagePullPolicy: IfNotPresent
  replicas: 1
