apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "productpage-inviz-app.fullname" . }}-bookinfo-productpage
  labels:
    account: productpage
  {{- include "productpage-inviz-app.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.bookinfoProductpage.serviceAccount.annotations | nindent 4 }}