apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ratings-inviz-app.fullname" . }}-ratings-v1
  labels:
    app: ratings
    version: v1
  {{- include "ratings-inviz-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ratingsV1.replicas }}
  selector:
    matchLabels:
      app: ratings
      version: v1
    {{- include "ratings-inviz-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: ratings
        version: v1
      {{- include "ratings-inviz-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.ratingsV1.ratings.image.repository }}:{{ .Values.ratingsV1.ratings.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.ratingsV1.ratings.imagePullPolicy }}
        name: ratings
        ports:
        - containerPort: 9080
        resources: {}
      serviceAccountName: {{ include "ratings-inviz-app.fullname" . }}-bookinfo-ratings