apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ratings-inviz-app.fullname" . }}-bookinfo-ratings
  labels:
    account: ratings
  {{- include "ratings-inviz-app.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.bookinfoRatings.serviceAccount.annotations | nindent 4 }}