apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "details-inviz-app.fullname" . }}-bookinfo-details
  labels:
    account: details
  {{- include "details-inviz-app.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.bookinfoDetails.serviceAccount.annotations | nindent 4 }}